### PR TITLE
Update dependencies to latest Joomla versions

### PR DESCRIPTION
**Pull request by wilsonge**
This updates the dependencies on the Joomla composer imports. I have also removed the renderer in favour of the framework v2 package

Note PR incomplete until this line: https://github.com/joomla-extensions/jstats-server/pull/1/files#diff-7c7968d089d08e0f3c6dc95e7effbd36R84 is fixed

### CODE REVIEW

**Comment by mbabker** [comment]
Two thoughts going forward:

1) Use `"joomla/view": "~2.0@dev"` also, at least then you've got a version of the View layer natively supporting the RendererInterface
2) Move the renderer instantiation into a service.  George you've got access to this - https://github.com/mbabker/michaels.website/blob/master/src/Service/TwigRendererProvider.php - use it as a base.

**Comment by mbabker** [comment]
I'm merging this and will deal with the folder path thing in a moment, can reverse that when we get around to updating the renderer package.

**Comment by wilsonge** [comment]
Yah - that was another thing I was working on - but wasn't sure about how I wanted to add the [stats service](https://github.com/joomla-extensions/jstats-server/blob/master/src/Stats/Renderer/Extensions/StatsExtension.php) because you don't want it to be in a provider as it's view specific - but at the same time adding it in the view means you may as well typehint the twig implementation rather than the generic renderer interface

**Comment by mbabker** [comment]
Just like I've done in my site's service provider, you add Twig extensions in there.  Basically, the provider should take care of loading up all the Twig stuff automagically and the views should be unaware of the specific implementation.

**Pull request merged**
